# Generated by Django 3.0.3 on 2020-06-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
